### ISSUE TITLE
Navbar-js

### ISSUE THREAD

**Issue by lul-g** [lul-g/LoadSecure_new#2]
### TODO

- [ ] outside of navbar click should collapse navbar
- [ ] active nav should change on page scroll 
- [ ] header should fade out on scroll down and fade in on scroll up 
- [ ] Buble top-right(active tab indicator), should be fixed!!!

**Comment by abbiland** [comment]
- [ ] Have Logo in navbar go to home
- [ ] Remove "home" tab in navbar

**Comment by abbiland** [comment]
- [ ] Make "Log in to Portal" button go to https://portal.loadsecuresystems.com/
- [ ] Have all words in navbar (menu items and buttons) formatted in all caps
